### ISSUE TITLE
PIP or easy_install

### ISSUE THREAD

**Issue by chaliy** [luscoma/pyRazor#2]
Hello, is there any plans to add this to central catalog?

**Comment by bigabdoul** [comment]
> Honestly I had forgotten I wrote it. I may clean it up some and do that

This project seems appealing to me but nowhere on the internet can I find a simple documentation about how to get up and running. It would be great, as @chaliy outlined it here above, to push this to a central Python catalog and provide a sample integration code for Flask (for example).

**Comment by Yeganloo** [comment]
Front-End changed a lot by java-script platforms such as vue, react and etc.
If you think this project is still useful for you, it's OK, i will work on it a little more :)

**Comment by bigabdoul** [comment]
The thing is, I was trying out the Flask web framework and came across the template language they use by default: Jinja2. I don't like it and so I looked for something that uses a logic similar to the Razor View Engine. Your project is great. It just needs some adjustments so that it can be easier integrated into a Flask web project.

**Comment by Yeganloo** [comment]
OK. I'm on it.
But will take a little time ;)

**Comment by Yeganloo** [comment]
@luscoma i need your email address to mention it in package pile plz.

**Comment by bigabdoul** [comment]
OK, here it is; but I will delete this comment upon your confirmation: kababdoul@hotmail.com

**Comment by Yeganloo** [comment]
Thanks. but i need @luscoma email address. not yours :D
If he did not answer in next 8 hours, i will use a temporary email address to release the package.

**Comment by bigabdoul** [comment]
> Thanks. but i need @luscoma email address. not yours :D
> If he did not answer in next 8 hours, i will use a temporary email address to release the package.

Oh, sorry about that. I didn't pay attention to the @luscoma mention.

**Comment by luscoma** [comment]
I'm not really doing any work on this anymore so if you want to put yours
or his that's fine too.  Really appreciate you doing the work to add a
package for this!

Alex
